### ISSUE TITLE
Tankar, Funderingar o plugins

### ISSUE THREAD

**Issue by duadansenior** [Sketaful/Swedecraft#9]
Hej Skettis a.k.a Gud :D Hoppas allt är bra med dig, kan säga att jag älskar hur snabbt du uppdaterar servern samt att den är på svenska ^_^

Men har lite funderingar, tankar, åsikter o något enstaka klagomål :P om servern som jag gärna får svar på eller till och med åtgärdade.
Så låt oss sätta igång ;) ^^.

Ibland så är det lite server lagg, vilket verkar bero på att det är en aningen många plugins på servern, därför ifrågasätter jag vissa utav dem, varför vi har kvar dem eller om det går att modifiera dem för att de ska ta mindre kraft på servern. Det som märks tydligast är att monster kan frysa fast ibland i flera sekunder (ca 10-20) för att sedan ha fått ny uträknad position, med utdelad skada till spelaren utan man har haft möjlighet att försvara sig.

Jag har även märkt att det är sällan det är någon admin aktiv inne (mer än Thobbi) och i så fall har de varit inne väldigt kort tid! 
Så Kanske kan vara lämpligt att se efter om någon mer än thobbi till att vara staff, så Hen kan hjälpa till med att kolla efter greifs osv =)

Dessutom så undrar jag om jag får hjälpa till med att skapa fler Tags, som ska kunna finnas tillgängliga i shopen(som exempel hade jag tänkt mig tags
som höjer rpg känslan, främst som olika titlar och liknande: Greve/Grevinna, Tjuv, Bonde osv). Ännu bättre om det går att göra så de bara blir tillgängliga
om spelaren har uppfyllt vissa krav. =)

--------------------------------------------Positiva saker ----------------------------------------------------------------
☻TryMe - HA KVAR DEN! :D men behövs läggas till fler frågor.

--------------------------------------------Mods jag ifrågasätter speciellt---------------------------------------------

☻MyPet - Känns inte som om det är någon som använder denna modden, då de flesta va jag har hört spelar utan husdjur/pet även utan moddar.

☻MyPetNpc - gissar på att den tillhör föregående, men vad gör den?

☻AdvancedAchivements - roligt, men känns som det tar upp för mycket på servern. Åtminstone bör den modifieras väldigt mycket. Och personligen känns den mest irriternade.

☻AreaShop/MinecraftMarket/SignShop - Varför finns det 3 shop plugins? Används alla 3 eller kan någon tas bort. Vet ju att vi använder SignShop, men vad gör de andra?

☻AntiXray - Som Thobbi säger, det är lättare att ha några Moderatorer som är mer aktiva och kan kolla upp nya (som gamla spelare). Personligen tycker jag att den är  relativt bra att ha. Men bör tänkas över. Kan behövas modifieras, om den ska behållas (förslag: om man har spelat X timmar
så stängs den av för den spelaren, om det går att fixa).

☻ChatReaction - känns mest som den stör chatten, då den har komplicerade "ord"

☻Zhorse - småpraktisk men känns mest som resurskrävande för servern, då den enligt min mening sabbar rpg delen. 

☻CamerObscura - Går det aktivt att för spelare använda kameror eller vad gör modden? Känns också som att den tar upp server kapacitet.

☻ItemMakerPro - är det något för spelarna? Eller vad för den till för nytta?

☻EditAbleSigns - Känns inte som att man behöver en hel plugin för att skriva om en skylt. Eller medför den något mer som används?

☻ICJukebox - Den gör vadå? Kort så låter det som en plugin som loopar jukeboxes, men behövs det för spelarna? 

-----------------------------------Plugins som jag inte kunde hitta info om---------------------------------------
☻TextReplacer
☻CratesPLus
☻EasyCarts
☻MineCrates

**Comment by Sketaful** [comment]
Har tagit bort Mypet, Mypet NPC, Advanced Achievements, ChatReaction, Zhorse och EditableSigns.

Självklart får du komma på tags om du vill. All hjälp uppskattas. :)
